#!/bin/sh

uci -q batch <<'EOI'
set network.wan_vlan=device
set network.wan_vlan.type='8021q'
set network.wan_vlan.ifname='wan'
set network.wan_vlan.vid='40'
set network.wan_vlan.name='wan.40'
set network.wan.proto='pppoe'
set network.wan.username='CHANGE_ME_PPPoE_USERNAME'
set network.wan.password='CHANGE_ME_PPPoE_PASSWORD'
set network.wan.device='wan.40'
set network.wan.mtu='1492'
set network.wan.ipv6='auto'
set network.wan.keepalive='6 10'
set network.wan.demand='0'
set network.globals=globals
set network.globals.packet_steering='1'
set network.lan.ip6assign='64'
set network.wan6=interface
set network.wan6.proto='dhcpv6'
set network.wan6.device='@wan'
set network.wan6.reqaddress='try'
set network.wan6.reqprefix='auto'
EOI
uci commit network

uci -q batch <<'EOI'
set firewall.wan_ssh=rule
set firewall.wan_ssh.name='Allow-SSH-From-WAN'
set firewall.wan_ssh.src='wan'
set firewall.wan_ssh.proto='tcp'
set firewall.wan_ssh.dest_port='22'
set firewall.wan_ssh.target='ACCEPT'
set firewall.wan_ssh.enabled='1'
EOI
uci commit firewall

uci -q batch <<'EOI'
set dhcp.lan.dhcpv6='server'
set dhcp.lan.ra='server'
set dhcp.lan.ra_flags='managed-config other-config'
EOI
uci commit dhcp

exit 0
